sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: MySelf-username
    password: MySelf-password
  alioss:
    access-key-id:  MySelf-access-key-id
    access-key-secret:  MySelf-access-key-secret
    bucket-name:  MySelf-bucket-name
    endpoint:  MySelf-endpoint
  redis:
    host: localhost
    port: 6379
