sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    access-key-id: LTAI5tCaBfbgvCGihGkDxFHJ
    access-key-secret: ynEeV1EmtiROrN4T3PUMEcYBYFIuwi
    bucket-name: sky-take-out-yjs
    endpoint: oss-cn-beijing.aliyuncs.com
  redis:
    host: localhost
    port: 6379